### PR TITLE
Feature/model tests getter setter

### PR DESCRIPTION
**Pull request by ebersold**
Tests for non-trivial getters and setters of model classes.

### CODE REVIEW

**Comment by wherget** [comment]
Should we be using Hamcrest matchers instead of TestNG Asserts for consistency reasons?
Also I'm thinking of wanting to know how good the branch coverage for these tests is...

**Comment by wherget** [comment]
Okay, I've checked coverage locally, the following points are still open for testing:
- [x] `PrefabSet.isChildOf` is also true for grandchildren
- [x] `SceneNode.isChildOf` is also true for grandchildren
- [x] Trying `Project.addScenario(null)` should throw
- [x] `Project.addScenario` of a Scenario that is currently part of another Project should reparent.
- [x] `Project.removeScenario` of a Scenario that is currently part of this Project should set that scenario's Project to `null`.

€dit: updated with results of coverage test after checking both branches combined as per @spidan's comment

**Comment by spidan** [comment]
The tests for adding scenarios to or removing them from projects are already implemented on the more general feature/model-tests branch.

**Comment by wherget** [comment]
Should be good now. I was debating whether the parent-sibling case should be a separate test case, but there _is_ such a thing as overdoing it.

**Pull request merged**
